# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Me"
  url = "#about"
  weight = 10


# [[main]]
#   name = "WebScraping"
#   url = "/webscraping"
#   weight = 2

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 1

[[main]]
 name = "Blog"
 url = "#posts"
 weight = 5

# [[main]]
#   name = "Tags"
#   url = "#tags"
#   weight = 10

[[main]]
  name = "Skills"
  url = "#skills"
  weight = 15


# [[main]]
#   name = "R"
#   url = "/r"
#   weight = 20

# [[main]]
#   name = "Python"
#   url = "/python"
#   weight = 30

# [[python]]
#   name = "Python"
#   url = "/python"
#   identifier = "python"

# [[main]]
#    name = "Miscellaneous"
#    url = "/miscellaneous"
#    weight = 40



# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40
# [[courses]]
#   name = "Overview"
#   weight = 1
#   url = "/courses/"

[[miscellaneous]]
  name = "Multilinguistic problems in NLP"
  weight = 3
  identifier = "multilinguisme"

# [[courses]]
#   name = "Blog"
#   weight = 2
#   identifier = "blog"

[[main_right]]
  name = "<i class=\"fab fa-github-alt\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/xiaoouwang"
  weight = 1

[[main_right]]
  name = "<i class=\"fas fa-comments\" style=\"color: rgb(123, 22, 255); font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://spectrum.chat/data-science?tab=posts"
  weight = 3

[[main_right]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/xiaoouwangfr"
  weight = 2

# [[main]]
#   name = "Tableaux"
#   url = "test/"
#   weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
