options(blogdown.ext = ".Rmd", blogdown.author = "Xiaoou WANG")
Sys.setenv(RETICULATE_PYTHON = '/Users/rosingle/opt/anaconda3/bin/python')
options(crayon.enabled=FALSE)
# important to load stats before dplyr (tidyverse)
# options(servr.daemon = TRUE)
library(stats)
# library(reshape)
# library(plyr)
# library(ggpubr)
# library(DSUR.noof)
# library(languageR)
library(tidyverse)
